-- atividade bd2

CREATE DATABASE bdpratica02;
USE bdpratica02;

CREATE TABLE DEPARTAMENTO(
    DEP_COD INT(4),
    DEP_NOM VARCHAR(30) NOT NULL,
    DEP_DAT_INI DATE,
    PRIMARY KEY (DEP_COD)
);

CREATE TABLE FUNCIONARIO(
    FUN_COD INT(4),
    FUN_NOM VARCHAR(100) NOT NULL,
    FUN_CPF VARCHAR(15) UNIQUE,
    FUN_SAL DECIMAL(4,2) CHECK (FUN_SAL >= 1000.00),
    FUN_END VARCHAR(252),
    FUN_SEX CHAR(1) CHECK (FUN_SEX IN ('M','F')),
    FUN_SUP INT(4),
    DEP_COD INT(4),
    PRIMARY KEY (FUN_COD),
    FOREIGN KEY (FUN_SUP) REFERENCES FUNCIONARIO(FUN_COD),
    FOREIGN KEY (DEP_COD) REFERENCES DEPARTAMENTO(DEP_COD)
);

CREATE TABLE LOCALIZACAO(
    DEP_COD INT(4),
    LOC_DES VARCHAR(252),
    PRIMARY KEY (DEP_COD, LOC_DES),
    FOREIGN KEY (DEP_COD) REFERENCES DEPARTAMENTO(DEP_COD)
);

CREATE TABLE DEPENDENTE(
    FUN_COD INT(4),
    DEN_SEQ INT(4),
    DEN_NOM VARCHAR(100) NOT NULL,
    DEN_PAR VARCHAR(30) NOT NULL CHECK (DEN_PAR IN ('PAI','MÃE','IRMAOS','FILHO')),
    DEN_DAT_NASC DATE,
    PRIMARY KEY (FUN_COD, DEN_SEQ),
    FOREIGN KEY (FUN_COD) REFERENCES FUNCIONARIO(FUN_COD)
);

CREATE TABLE PROJETO(
    PRO_COD INT(4),
    DEP_COD INT(4),
    PRO_TIT VARCHAR(150) NOT NULL,
    PRO_DES VARCHAR(252),
    PRO_DAT_CAD DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (PRO_COD),
    FOREIGN KEY (DEP_COD) REFERENCES DEPARTAMENTO(DEP_COD)
);

CREATE TABLE PARTICIPA(
    FUN_COD INT(4),
    PRO_COD INT(4),
    PAR_HOR VARCHAR(50),
    PRIMARY KEY (FUN_COD, PRO_COD),
    FOREIGN KEY (FUN_COD) REFERENCES FUNCIONARIO(FUN_COD),
    FOREIGN KEY (PRO_COD) REFERENCES PROJETO(PRO_COD)
);